sudo : required
services:
  - docker

before_install:
  - docker build -t sagim//react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sagim/react-test npm test -- --coverage

after_success:
  - docker build -t sagim/multi-client ./client
  - docker build -t sagim/multi-nginx ./nginx
  - docker build -t sagim/multi-server ./server
  - docker build -t sagim/multi-worker ./worker

  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push to docker.hub
  - docker push sagim/multi-client
  - docker push sagim/multi-nginx
  - docker push sagim/multi-server
  - docker push sagim/multi-worker